name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and test frontend
        run: |
          cd frontend
          docker build -t favegaleon/frontend-img:v1 .
          docker push favegaleon/frontend-img:v1
          go build
          go test ./...
