name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and test frontend
        run: |
          cd frontend
          go build
          go test ./...
          docker build -t ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}/${{ COOKIE_PROJECT.DOCKER_USERNAME }}/frontend:v1 .
          echo ${{ COOKIE_PROJECT.DOCKER_PASSWORD }} | docker login ${{ COOKIE_PROJECT.DOCKER_REGISTRY }} -u ${{ COOKIE_PROJECT.DOCKER_USERNAME }} --password-stdin
          docker push ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}/${{ COOKIE_PROJECT.DOCKER_USERNAME }}/frontend:v1
        env:
          DOCKER_REGISTRY: ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ COOKIE_PROJECT.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ COOKIE_PROJECT.DOCKER_PASSWORD }}

      - name: Build backend
        run: |
          cd backend
          docker build -t ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}/${{ COOKIE_PROJECT.DOCKER_USERNAME }}/backend:v1 .
          echo ${{ COOKIE_PROJECT.DOCKER_PASSWORD }} | docker login ${{ COOKIE_PROJECT.DOCKER_REGISTRY }} -u ${{ COOKIE_PROJECT.DOCKER_USERNAME }} --password-stdin
          docker push ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}/${{ COOKIE_PROJECT.DOCKER_USERNAME }}/backend:v1
        env:
          DOCKER_REGISTRY: ${{ COOKIE_PROJECT.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ COOKIE_PROJECT.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ COOKIE_PROJECT.DOCKER_PASSWORD }}
          
